name: podever
favicon: null
layout_spectrum: 0.11837377003394067
typography_spectrum: 0.2750370670109987
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7227628757245839
  lightness: 0.21854117163456976
  saturation: 0.409715473651886
  rhythmicContrast: 0.1989451872650534
purpose: []
